{
 "title": "ActaDevis Back",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "microsoftaspnetcorehosting_requests_per_second{job=\"monitor\"}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "microsoftaspnetcorehosting_total_requests{job=\"monitor\"}"
    }
   ]
  },
  {
   "title": "Current requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "microsoftaspnetcorehosting_current_requests{job=\"monitor\"}"
    }
   ]
  },
  {
   "title": "Failed requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "microsoftaspnetcorehosting_failed_requests{job=\"monitor\"}"
    }
   ]
  },
  { "title": "Dotnet", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Exceptions count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "systemruntime_exception_count{job=\"monitor\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Mo" } },
   "targets": [
    {
     "expr": "systemruntime_working_set_bytes{job=\"monitor\"}/1000000"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "systemruntime_cpu_usage_ratio{job=\"monitor\"}"
    }
   ]
  },
  {
   "title": "Generation Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "systemruntime_gen_0_size_bytes{job=\"monitor\"}"
    }
   ]
  },
  {
   "title": "Overall Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "systemruntime_gen_0_size_bytes{job=\"monitor\"}"
    }
   ]
  },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "systemruntime_time_in_gc_ratio{job=\"monitor\"}",
     "legendFormat": "% Time in GC"
    }
   ]
  },
  {
   "title": "Allocations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "systemruntime_alloc_rate_bytes{job=\"monitor\"}"
    }
   ]
  },
  {
   "title": "GC Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "systemruntime_gc_fragmentation_ratio{job=\"monitor\"}",
     "legendFormat": "Total Fragmentation"
    }
   ]
  }
 ]
}